# frozen_string_literal: true

require 'rake/testtask'
require_relative 'src/accuracy_reporter'
require_relative 'src/training_data_formatter'

task default: :test

desc 'Export the accuracy score report to Botpress'
Rake::Task.define_task(:export_accuracy_score_report) do
  endpoint = BotpressEndpoint.new(
    scheme: 'https',
    host: 'oasist-botpress-server.herokuapp.com',
    bot_id: 'sample-bot',
    user_id: 'oasist'
  )
  path_to_accuracy_score_chart = File.join('..', 'csv')
  path_to_test_data            = File.join(path_to_accuracy_score_chart, 'test_data.csv')

  AccuracyReporter.run(endpoint:, path_to_test_data:, path_to_accuracy_score_chart:)
  puts "--- Successfully exported accuracy score chart under #{path_to_accuracy_score_chart}/ ---"
end

desc 'Format the CSV test data to JSON and export'
Rake::Task.define_task(:format_test_data) do
  path_to_csv_training_data  = File.join('..', 'csv', 'training_data.csv')
  path_to_json_training_data = File.join('..', 'json')

  training_data_formatter = TrainingDataFormatter.new(path_to_csv_training_data)
  training_data_formatter.export(path_to_json_training_data)
  puts "--- Successfully exported JSON training data under #{path_to_json_training_data}/ ---"
end

desc 'Run all tests'
Rake::TestTask.new do |task|
  task.pattern = File.join('.', '**', '*_test.rb')
end
