# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby file: '.ruby-version'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 8.1.3'
# Use Puma as the app server
gem 'puma', '~> 8.0.2'
# The original asset pipeline for Rails [https://github.com/rails/sprockets-rails]
gem 'sprockets-rails', '~> 3.5.2'

gem 'dotenv-rails', '~> 3.2.0'

gem 'rexml', '~> 3.4.4'

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '~> 1.24.6', require: false

# CSV
gem 'csv', '~> 3.3.5'

# Data structure, similar to a Hash, that allows the definition of arbitrary attributes with their accompanying values
gem 'ostruct', '~> 0.6.3'

# CGI: used transitively by Rails (cookie/session escaping). Formerly a default
# gem; pinned explicitly so Bundler/RBS can resolve it from Gemfile.lock.
gem 'cgi', '~> 0.5.0'

group :development, :test do
  # Debug tool used with binding.irb. Explicit require avoids eager loading `debug/prelude`
  # which interferes with the Docker boot process.
  # [Ref] https://ruby.github.io/irb/#label-Debugging+with+IRB
  # [Ref] https://github.com/ruby/debug#debug-command-on-the-debug-console
  # [Ref] https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem 'debug', platforms: %i[mri windows], require: false
end

group :development do
  # Access an interactive console on exception pages or by calling 'console' anywhere in the code.
  gem 'web-console', '~> 4.3.0'
  # Display performance information such as SQL time and flame graphs for each request in your browser.
  # Can be configured to work on production as well see: https://github.com/MiniProfiler/rack-mini-profiler/blob/master/README.md
  gem 'rack-mini-profiler', '~> 4.0.1'
  # Static code analysis for security vulnerabilities
  gem 'brakeman', '~> 8.0.4', require: false
  # RuboCop
  gem 'rubocop', '~> 1.86.2', require: false
  gem 'rubocop-performance', '~> 1.26.0', require: false
  gem 'rubocop-rails', '~> 2.35.3', require: false
  gem 'rubocop-rspec', '~> 3.9.0', require: false
  gem 'rubocop-rspec_rails', '~> 2.32.0', require: false
  # Typechecking
  gem 'rbs-inline', '~> 0.14.0', require: false
  gem 'rbs_rails', '~> 0.13.1', require: false
  gem 'steep', '~> 2.0.0', require: false
end

group :test do
  gem 'rspec-rails', '~> 8.0.4'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: %i[windows jruby]
