# This workflow uses actions that are not certified by GitHub.  They are
# provided by a third-party and are governed by separate terms of service,
# privacy policy, and support documentation.
#
# This workflow will install a prebuilt Ruby version, install dependencies, and
# run tests and linters.

name: Ruby on Rails - CI

on:
  push:
    branches:
      - master
    paths:
      - .github/actions/setup-ruby-on-rails/action.yml
      - .github/workflows/ruby-on-rails--ci.yml
      - .ruby-version
      - ruby-on-rails/.ruby-version
      - ruby-on-rails/Gemfile
      - ruby-on-rails/Gemfile.lock
      - ruby-on-rails/Rakefile
      - ruby-on-rails/.rubocop.yml
      - ruby-on-rails/.rubocop_todo.yml
      - ruby-on-rails/Steepfile
      - ruby-on-rails/**/*.rb
      - ruby-on-rails/**/*.rbs
      - ruby-on-rails/**/*.rake
      - ruby-on-rails/**/*.yml
      - ruby-on-rails/**/*.js
      - ruby-on-rails/**/*.css
      - ruby-on-rails/**/*.html.erb
      - ruby-on-rails/**/*.csv
      - ruby-on-rails/**/*.json
  pull_request:
    paths:
      - .github/actions/setup-ruby-on-rails/action.yml
      - .github/workflows/ruby-on-rails--ci.yml
      - .ruby-version
      - ruby-on-rails/.ruby-version
      - ruby-on-rails/Gemfile
      - ruby-on-rails/Gemfile.lock
      - ruby-on-rails/Rakefile
      - ruby-on-rails/.rubocop.yml
      - ruby-on-rails/.rubocop_todo.yml
      - ruby-on-rails/Steepfile
      - ruby-on-rails/**/*.rb
      - ruby-on-rails/**/*.rbs
      - ruby-on-rails/**/*.rake
      - ruby-on-rails/**/*.yml
      - ruby-on-rails/**/*.js
      - ruby-on-rails/**/*.css
      - ruby-on-rails/**/*.html.erb
      - ruby-on-rails/**/*.csv
      - ruby-on-rails/**/*.json

permissions:
  contents: read
  pull-requests: read

jobs:
  change-detection:
    runs-on: ubuntu-latest
    outputs:
      ruby-changes: ${{ steps.change-detection.outputs.ruby }}
      rubocop-changes: ${{ steps.change-detection.outputs.rubocop}}
      steep-changes: ${{ steps.change-detection.outputs.steep}}
    steps:
      - uses: actions/checkout@v7
      - name: Change Detection
        uses: dorny/paths-filter@v4
        id: change-detection
        with:
          filters: |
            ruby:
              - .github/actions/setup-ruby-on-rails/action.yml
              - .github/workflows/ruby-on-rails--ci.yml
              - .ruby-version
              - ruby-on-rails/.ruby-version
              - ruby-on-rails/Gemfile
              - ruby-on-rails/Gemfile.lock
              - ruby-on-rails/Rakefile
              - ruby-on-rails/**/*.rb
              - ruby-on-rails/**/*.rake
              - ruby-on-rails/**/*.yml
              - ruby-on-rails/**/*.js
              - ruby-on-rails/**/*.css
              - ruby-on-rails/**/*.html.erb
              - ruby-on-rails/**/*.csv
              - ruby-on-rails/**/*.json
            rubocop:
              - .github/actions/setup-ruby-on-rails/action.yml
              - .github/workflows/ruby-on-rails--ci.yml
              - .ruby-version
              - ruby-on-rails/.ruby-version
              - ruby-on-rails/Gemfile
              - ruby-on-rails/Gemfile.lock
              - ruby-on-rails/Rakefile
              - ruby-on-rails/.rubocop.yml
              - ruby-on-rails/.rubocop_todo.yml
              - ruby-on-rails/**/*.rb
              - ruby-on-rails/**/*.rake
            steep:
              - .github/actions/setup-ruby-on-rails/action.yml
              - .github/workflows/ruby-on-rails--ci.yml
              - .ruby-version
              - ruby-on-rails/.ruby-version
              - ruby-on-rails/Gemfile
              - ruby-on-rails/Gemfile.lock
              - ruby-on-rails/Rakefile
              - ruby-on-rails/Steepfile
              - ruby-on-rails/**/*.rb
              - ruby-on-rails/**/*.rbs
              - ruby-on-rails/**/*.rake
  rspec:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    needs: change-detection
    if: needs.change-detection.outputs.ruby-changes == 'true'
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/setup-ruby-on-rails
      - name: RSpec
        working-directory: ./ruby-on-rails
        run: bundle exec rspec
  brakeman:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    needs: change-detection
    if: needs.change-detection.outputs.ruby-changes == 'true'
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/setup-ruby-on-rails
      - name: Brakeman
        working-directory: ./ruby-on-rails
        run: bundle exec brakeman --no-pager
  rubocop:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    needs: change-detection
    if: needs.change-detection.outputs.rubocop-changes == 'true'
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/setup-ruby-on-rails
      - name: RuboCop
        working-directory: ./ruby-on-rails
        run: bundle exec rubocop
  steep:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    needs: change-detection
    if: needs.change-detection.outputs.steep-changes == 'true'
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/setup-ruby-on-rails
      - name: Steep
        working-directory: ./ruby-on-rails
        run: bundle exec steep check
